- name: Test
  hosts: localhost
  gather_facts: yes
  tasks:
  - block:
    - name: Update repos and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      tags:
        - updateall
        - fullup
    - name: Upgrade all packages
      become: yes
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
      tags:
        - upgradeall
        - fullup
    - name: Install all apps
      become: true
      ansible.builtin.apt:
        name: ["curl", "wget", "software-properties-common", "apt-transport-https", "docker", "git", "zsh"]
      tags:
        - install
        - prod
    - name: Change shell
      become: true
      ansible.builtin.shell: |
        sudo chsh -s $(which zsh)
      changed_when: true
    - name: Install deno
      become: true
      become_user: matt
      ansible.builtin.shell: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
      failed_when: false
      changed_when: false
    - name: Install bun
      become: true
      become_user: matt
      ansible.builtin.shell: |
        curl -fsSL https://bun.sh/install | bash
      failed_when: false
      changed_when: false
    - name: Install node repo
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_19.x | sh
      failed_when: false
      changed_when: false
    - name: Install node package
      ansible.builtin.apt:
        name: nodejs
        update_cache: true
    - name: Install Rust
      become: true
      become_user: matt
      ansible.builtin.shell: |
        curl https://sh.rustup.rs --output rust.sh
        chmod +x ./rust.sh
        ./rust.sh -y
        rm ./rust.sh
      failed_when: false
      changed_when: false
    - name: Install Starship
      become: true
      ansible.builtin.shell: |
        curl https://starship.rs/install.sh --output starship.sh
        chmod +x ./starship.sh
        ./starship.sh -y
        rm ./starship.sh
      failed_when: false
      changed_when: false
    - name: Configure Docker
      become: true
      ansible.builtin.shell: |
        addgroup --system docker
        adduser $USER docker
        newgrp docker
        usermod -aG docker $USER
      failed_when: false
      changed_when: false
    - name: Configure ZSHRC
      become: true
      become_user: matt
      ansible.builtin.shell: |
        curl 'https://raw.githubusercontent.com/Hamm1/devbox/main/zshrc' --output /home/$(whoami)/.zshrc
      failed_when: false
      changed_when: false
    when: ansible_os_family == "Debian"
    
  - block:
    - name: Install Arch packages
      become: true
      community.general.pacman:
        name: ["curl", "wget", "software-properties-common", "apt-transport-https", "docker", "git", "zsh"]
    when: ansible_os_family == "Arch"
