- name: Test
  vars:
    user: matt
  gather_facts: true
  tasks:
    - name: Ubuntu
      block:
        - name: Update repos and cache
          ansible.builtin.apt:
            update_cache: true
            force_apt_get: true
            cache_valid_time: 3600
          tags:
            - updateall
            - fullup
        - name: Upgrade all packages
          become: true
          ansible.builtin.apt:
            upgrade: dist
            force_apt_get: true
          tags:
            - upgradeall
            - fullup
        - name: Install all apps
          become: true
          ansible.builtin.apt:
            name:
              - curl
              - wget
              - software-properties-common
              - apt-transport-https
              - docker
              - git
              - zsh
          tags:
            - install
            - prod
        - name: Change shell
          become: true
          ansible.builtin.shell: |
            sudo chsh -s $(which zsh)
          changed_when: true
        - name: Download deno
          become: true
          become_user: "{{ user }}"
          ansible.builtin.get_url:
            url: 'https://deno.land/x/install/install.sh'
            dest: ./deno.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install deno
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./deno.sh
            rm -rf deno.sh
          failed_when: false
          changed_when: false
        - name: Download bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.get_url:
            url: 'https://bun.sh/install'
            dest: ./bun.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./bun.sh
            rm -rf bun.sh
          failed_when: false
          changed_when: false
        - name: Download node
          become: true
          ansible.builtin.get_url:
            url: 'https://deb.nodesource.com/setup_19.x'
            dest: ./node.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install node repo
          ansible.builtin.shell: |
            ./node.sh
            rm -rf node.sh
          failed_when: false
          changed_when: false
        - name: Install node package
          ansible.builtin.apt:
            name: nodejs
            update_cache: true
        - name: Download Rust
          become: true
          ansible.builtin.get_url:
            url: 'https://sh.rustup.rs'
            dest: ./rust.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install Rust
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./rust.sh -y
            rm ./rust.sh
          failed_when: false
          changed_when: false
        - name: Download Starship
          become: true
          ansible.builtin.get_url:
            url: 'https://starship.rs/install.sh'
            dest: ./starship.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install Starship
          become: true
          ansible.builtin.shell: |
            ./starship.sh -y
            rm ./starship.sh
          failed_when: false
          changed_when: false
        - name: Configure Docker
          become: true
          ansible.builtin.shell: |
            addgroup --system docker
            adduser $USER docker
            newgrp docker
            usermod -aG docker $USER
          failed_when: false
          changed_when: false
        - name: Configure ZSHRC
          become: true
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/Hamm1/devbox/main/zshrc'
            dest: /home/{{ user }}/.zshrc
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install zsh Auto Suggestions # noqa latest[git]
          become: true
          ansible.builtin.git:
            repo: https://github.com/zsh-users/zsh-autosuggestions
            dest: "/home/{{ user }}/.zsh/zsh-autosuggestions"
            clone: true
