- name: Test
  hosts: all
  vars:
    user: matt
  gather_facts: true
  tasks:
    - name: Ubuntu
      when: ansible_os_family == "Debian"
      block:
        - name: Update repos and cache
          ansible.builtin.apt:
            update_cache: true
            force_apt_get: true
            cache_valid_time: 3600
          tags:
            - updateall
            - fullup
          become: true
        - name: Upgrade all packages
          ansible.builtin.apt:
            upgrade: dist
            force_apt_get: true
          tags:
            - upgradeall
            - fullup
          become: true
          become_user: root
        - name: Install all apps
          ansible.builtin.apt:
            name:
              - curl
              - wget
              - software-properties-common
              - apt-transport-https
              - docker
              - git
              - zsh
          tags:
            - install
            - prod
          become: true
          become_user: "{{ user }}"
        - name: Change shell
          become: true
          ansible.builtin.shell: |
            sudo chsh -s $(which zsh)
          changed_when: true
        - name: Download deno
          become: true
          become_user: "{{ user }}"
          ansible.builtin.get_url:
            url: 'https://deno.land/x/install/install.sh'
            dest: ./deno.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install deno
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./deno.sh
            rm -rf deno.sh
          failed_when: false
          changed_when: false
        - name: Download bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.get_url:
            url: 'https://bun.sh/install'
            dest: ./bun.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./bun.sh
            rm -rf bun.sh
          failed_when: false
          changed_when: false
        - name: Download node
          become: true
          ansible.builtin.get_url:
            url: 'https://deb.nodesource.com/setup_19.x'
            dest: ./node.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install node repo
          ansible.builtin.shell: |
            ./node.sh
            rm -rf node.sh
          failed_when: false
          changed_when: false
        - name: Install node package
          ansible.builtin.apt:
            name: nodejs
            update_cache: true
        - name: Download Rust
          become: true
          ansible.builtin.get_url:
            url: 'https://sh.rustup.rs'
            dest: ./rust.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install Rust
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./rust.sh -y
            rm ./rust.sh
          failed_when: false
          changed_when: false
        - name: Download Starship
          become: true
          ansible.builtin.get_url:
            url: 'https://starship.rs/install.sh'
            dest: ./starship.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install Starship
          become: true
          ansible.builtin.shell: |
            ./starship.sh -y
            rm ./starship.sh
          failed_when: false
          changed_when: false
        - name: Configure Docker
          become: true
          ansible.builtin.shell: |
            addgroup --system docker
            adduser $USER docker
            newgrp docker
            usermod -aG docker $USER
          failed_when: false
          changed_when: false
        - name: Configure ZSHRC
          become: true
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/Hamm1/devbox/main/zshrc'
            dest: /home/{{ user }}/.zshrc
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install zsh Auto Suggestions # noqa latest[git]
          become: true
          ansible.builtin.git:
            repo: https://github.com/zsh-users/zsh-autosuggestions
            dest: "/home/{{ user }}/.zsh/zsh-autosuggestions"
            clone: true
    - name: Archlinux
      when: ansible_os_family == "Archlinux"
      block:
        - name: Update Pacman database
          become: true
          ansible.builtin.shell: |
            sudo pacman -Syy
            sudo pacman -S gst-plugins-base gst-plugins-base-libs webkit2gtk webkit2gtk-4.1 --noconfirm
            sudo pacman -S appmenu-gtk-module gtk3 libappindicator-gtk3 librsvg libvips --noconfirm
            sudo pacman -S wget openssl curl docker rust-src llvm-libs nodejs npm zsh starship deno unzip --noconfirm
          failed_when: false
          changed_when: false
        - name: Download yay # noqa latest[git]
          become: true
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: ./yay
            clone: true
        - name: Install yay
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            sudo chown -R {{ user }}:{{ user }} ./yay
            cd yay
            makepkg -si --noconfirm
            cd ..
            sudo rm -rf yay
          failed_when: false
          changed_when: false
        - name: Change shell
          become: true
          ansible.builtin.shell: |
            sudo chsh -s $(which zsh)
          changed_when: true
        - name: Download bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.get_url:
            url: 'https://bun.sh/install'
            dest: ./bun.sh
            mode: a+x
          failed_when: false
          changed_when: false
        - name: Install bun
          become: true
          become_user: "{{ user }}"
          ansible.builtin.shell: |
            ./bun.sh
            rm -rf bun.sh
          failed_when: false
          changed_when: false
        - name: Configure ZSHRC
          become: true
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/Hamm1/devbox/main/zshrc'
            dest: /home/{{ user }}/.zshrc
            mode: '0755'
          failed_when: false
          changed_when: false
        - name: Configure pacman
          become: true
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/Hamm1/devbox/main/pacman.conf'
            dest: /etc/pacman.conf
            mode: '0755'
          failed_when: false
          changed_when: false
        - name: Install zsh Auto Suggestions # noqa latest[git]
          become: true
          ansible.builtin.git:
            repo: https://github.com/zsh-users/zsh-autosuggestions
            dest: "/home/{{ user }}/.zsh/zsh-autosuggestions"
            clone: true
        - name: Install VSCode
          become: true
          ansible.builtin.shell: |
            yay -S visual-studio-code-bin --noconfirm
          failed_when: false
          changed_when: false
